/**
 * GET_WILD_PRICE_USD action types
 */
export const GET_WILD_PRICE_USD_REQUEST = 'GET_WILD_PRICE_USD_REQUEST';
export const GET_WILD_PRICE_USD_SUCCESS = 'GET_WILD_PRICE_USD_SUCCESS';
export const GET_WILD_PRICE_USD_ERROR = 'GET_WILD_PRICE_USD_ERROR';

/**
 * GET_LOOT_PRICE_USD action types
 */
export const GET_LOOT_PRICE_USD_REQUEST = 'GET_LOOT_PRICE_USD_REQUEST';
export const GET_LOOT_PRICE_USD_SUCCESS = 'GET_LOOT_PRICE_USD_SUCCESS';
export const GET_LOOT_PRICE_USD_ERROR = 'GET_LOOT_PRICE_USD_ERROR';
