'use strict';
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, '__esModule', { value: true });
exports.ZStakePoolFactory__factory = void 0;
const ethers_1 = require('ethers');
const _abi = [
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'previousOwner',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'newOwner',
				type: 'address',
			},
		],
		name: 'OwnershipTransferred',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'address',
				name: 'account',
				type: 'address',
			},
		],
		name: 'Paused',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: '_by',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'poolToken',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'poolAddress',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint64',
				name: 'weight',
				type: 'uint64',
			},
			{
				indexed: false,
				internalType: 'bool',
				name: 'isFlashPool',
				type: 'bool',
			},
		],
		name: 'PoolRegistered',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'address',
				name: 'account',
				type: 'address',
			},
		],
		name: 'Unpaused',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: '_by',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'poolAddress',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint32',
				name: 'weight',
				type: 'uint32',
			},
		],
		name: 'WeightUpdated',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: '_by',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'newIlvPerBlock',
				type: 'uint256',
			},
		],
		name: 'WildRatioUpdated',
		type: 'event',
	},
	{
		inputs: [],
		name: 'blockNumber',
		outputs: [
			{
				internalType: 'uint256',
				name: '',
				type: 'uint256',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: 'poolAddr',
				type: 'address',
			},
			{
				internalType: 'uint32',
				name: 'weight',
				type: 'uint32',
			},
		],
		name: 'changePoolWeight',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'uint256',
				name: 'perBlock',
				type: 'uint256',
			},
		],
		name: 'changeRewardTokensPerBlock',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: 'poolToken',
				type: 'address',
			},
		],
		name: 'getPoolAddress',
		outputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '_poolToken',
				type: 'address',
			},
		],
		name: 'getPoolData',
		outputs: [
			{
				components: [
					{
						internalType: 'address',
						name: 'poolToken',
						type: 'address',
					},
					{
						internalType: 'address',
						name: 'poolAddress',
						type: 'address',
					},
					{
						internalType: 'uint32',
						name: 'weight',
						type: 'uint32',
					},
					{
						internalType: 'bool',
						name: 'isFlashPool',
						type: 'bool',
					},
				],
				internalType: 'struct zStakePoolFactory.PoolData',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getRewardTokensPerBlock',
		outputs: [
			{
				internalType: 'uint256',
				name: '',
				type: 'uint256',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '_rewardToken',
				type: 'address',
			},
			{
				internalType: 'address',
				name: '_rewardsVault',
				type: 'address',
			},
			{
				internalType: 'uint192',
				name: '_rewardTokensPerBlock',
				type: 'uint192',
			},
		],
		name: 'initialize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'initializeImplementation',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'owner',
		outputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'paused',
		outputs: [
			{
				internalType: 'bool',
				name: '',
				type: 'bool',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		name: 'poolExists',
		outputs: [
			{
				internalType: 'bool',
				name: '',
				type: 'bool',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		name: 'pools',
		outputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: 'poolAddr',
				type: 'address',
			},
		],
		name: 'registerPool',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'renounceOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'rewardToken',
		outputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'rewardVault',
		outputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalWeight',
		outputs: [
			{
				internalType: 'uint32',
				name: '',
				type: 'uint32',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: 'newOwner',
				type: 'address',
			},
		],
		name: 'transferOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '_to',
				type: 'address',
			},
			{
				internalType: 'uint256',
				name: '_amount',
				type: 'uint256',
			},
		],
		name: 'transferRewardYield',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
];
class ZStakePoolFactory__factory {
	static createInterface() {
		return new ethers_1.utils.Interface(_abi);
	}
	static connect(address, signerOrProvider) {
		return new ethers_1.Contract(address, _abi, signerOrProvider);
	}
}
exports.ZStakePoolFactory__factory = ZStakePoolFactory__factory;
ZStakePoolFactory__factory.abi = _abi;
//# sourceMappingURL=ZStakePoolFactory__factory.js.map
