/**
 * SET_NAVBAR_TITLE action types
 */
export const SET_NAVBAR_TITLE = 'SET_NAVBAR_TITLE';

/**
 * SET_NAVBAR_SEARCHING_STATUS action types
 */
export const SET_NAVBAR_SEARCHING_STATUS = 'SET_NAVBAR_SEARCHING_STATUS';
