/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Registry } from "./Registry";

export { Registry__factory } from "./factories/Registry__factory";
